### ISSUE TITLE
MTP not working

### ISSUE THREAD

**Issue by 1aladdin1** [CaptainThrowback/android_device_htc_m8#4]
as mentioned in title: MTP doesn't work in build twrp-3.3.1-0_CPTB-20191022-03-m8_SAR.img

[recovery_MTP-fail.log](https://github.com/CaptainThrowback/android_device_htc_m8/files/3883944/recovery_MTP-fail.log)
[dmesg_MTP-fail.log](https://github.com/CaptainThrowback/android_device_htc_m8/files/3883945/dmesg_MTP-fail.log)

**Comment by CaptainThrowback** [comment]
This is a known issue. It's listed in the initial release note, and has not been fixed (and probably won't be).
