### ISSUE TITLE
mountpoint of system partition

### ISSUE THREAD

**Issue by 1aladdin1** [CaptainThrowback/android_device_htc_m8#5]
I used your SAR-recovery to install LineageOS 17. This worked fine.

Then I tried to restore a migrate backup - refer to this [XDA-thread](https://forum.xda-developers.com/android/apps-games/app-migrate-custom-rom-migration-tool-t3862763). This failed because a script inside the zip tried to call /system/bin/awk, which was not found (see [my post](https://forum.xda-developers.com/showpost.php?p=81023737&postcount=1024) describing this issue). The awk binary is located in /system_root/bin instead - due to a different mountpoint of system-partition.

This could cause many installations to fail.

**Comment by CaptainThrowback** [comment]
/system_root is the correct mount point for SAR devices. There is a symlink from /system_root/system to /system by default, but in order for zip installations to succeed, it has to be deleted. The actual location of the binary is /system_root/system/bin. There is no adjustment to be made here.

EDIT: The proper way to determine where the binaries should be located is to check the path of the ANDROID_ROOT variable, and if it's system, use system/bin, but if it's system_root, use the longer path mentioned above. That's pretty basic logic which any app should be able to accommodate.
